- env.go
- env_test.go
> renamed default to envDefault

- env.go
- env_test.go
I have added support for multiple options in future usage
> Handle multiple options

- README.md
- env.go
- env_test.go
Hello!
We found that in our project we really wanted to represent floats in our env config. Therefore, here's a pull request to do just that. I implemented both float32 and float64 in addition to slice types. Unit tests and readme updated. Thanks!
> Added float types and float slices

- env.go
- env_test.go
- glide.yaml
also added glide.yaml for dependency management. solve this issue https://github.com/caarlos0/env/issues/23
> Adding Support for int64 

- README.md
- env.go
- env_test.go
Also updated the unit tests and the README.md
> Add uint data type

- env.go
- env_test.go
> Inner struct support

- env.go
- env_test.go
> fix unexported inner structs

- env.go
- env_test.go
refs https://github.com/caarlos0/env/issues/87#issuecomment-489183319
> fix: try TextUnmarshaller before other types

- env.go
**Issue**
https://github.com/caarlos0/env/issues/90
> Fix recursive pointer parsing

- README.md
- env.go
- env_test.go
> feat: improved custom parsers

- README.md
- env.go
- env_test.go
> docs/test: document how to use custom time formats

- README.md
- env.go
- env_test.go
> feat: notEmpty tag

- README.md
- env.go
- env_test.go
> feat: allow to prefix envs

- env_test.go
- env_windows_test.go
- go.mod
- go.sum
removes all dependencies.
the only one being used was for testing, implemented the methods we use in our tests themselves and removed the dep.
env will now be dependency-free 🤘
> feat: 0 dependencies

- env_unix_test.go
3 new test cases were added for `env_unix.go`. I can add more test cases if you want. 
Signed-off-by: GitHub <gozeloglu@gmail.com>
> test: add tests for env_unix.go

- README.md
This PR updates `README.md` to use `github.com/caarlos0/env/v7` package. Also, it removes the tab in the code example.
> docs: update to v7

- env.go
- env_test.go
implements #251, behind an optional flag for now.
> feat: use field name by default

- README.md
Some updates to the examples in Readme so that they are compatible with
the latest release that changed some function signatures.
> Update and fix examples in readme for v8.0.0

- README.md
Hi @caarlos0, what do you think about this tool https://github.com/g4s8/envdoc? Is it possible to mention it in the README file?
> docs: add related projects

- env.go
- env_test.go
> Fix issue parsing into ptr fields with value
