README.md
env.go
env_test.go
examples/first.go

Hey there - nice lib!
This PR adds support for []string, []int and []bool types and allows you to set a separator via the struct tag.
```
dselans:env dselans$ go test ./... -cover -v
=== RUN   TestParsesEnv
--- PASS: TestParsesEnv (0.00s)
=== RUN   TestEmptyVars
--- PASS: TestEmptyVars (0.00s)
=== RUN   TestPassAnInvalidPtr
--- PASS: TestPassAnInvalidPtr (0.00s)
=== RUN   TestPassReference
--- PASS: TestPassReference (0.00s)
=== RUN   TestInvalidBool
--- PASS: TestInvalidBool (0.00s)
=== RUN   TestInvalidInt
--- PASS: TestInvalidInt (0.00s)
=== RUN   TestInvalidBoolsSlice
--- PASS: TestInvalidBoolsSlice (0.00s)
=== RUN   TestParsesDefaultConfig
--- PASS: TestParsesDefaultConfig (0.00s)
=== RUN   TestParseStructWithoutEnvTag
--- PASS: TestParseStructWithoutEnvTag (0.00s)
=== RUN …
```

Support for slices of ints, bools and strings.

---

README.md
env.go
env_test.go

Fields with the `env` tag set can now also include an option string,
similar to the json package: e.g., `env:"VAR_NAME,required"`.
This commit adds support for the "required" option.
The option parsing logic is somewhat primitive.  Only a single option at
a time is respected, and only either no option or the `required` option.
Parse returns an error if the `required` option is set for the env tag and
the corresponding environment variable is empty.
If a new tag such as `envRequired:"true"` is preferred over the current option implementation, we can refactor and update the PR.

Introduce the env tag option 'required'.

---

env.go

I found a little bit inconvenient that if you a have multiple errors in your env settings the `env` package only returns the first one. So I fix it, run the code again and get the next one, fix it, run again ...
So it is nice when the error message contains all badly configured env errors.

Include all errors in a error message

---

.travis.yml
env.go
env_test.go

Before, the default value was used for string variables that are set to
the empty string in the environment. Now, we use the value of the
environment, if and only if it is set, and the default value otherwise,
that is, if the variable is not set in the environment.

Fixed handling of empty strings in the environment

---

env.go
env_test.go

if they are unitalized they should be ignored
closes #41

fixed inner struct

---

README.md
env.go
env_test.go
examples/first.go
parsers/README.md
parsers/parsers.go

Previous PR was based on an outdated fork. Woops! This should be better.
- Added support for `url.URL`
- Added support for custom parsers via `ParseWithFuncs()` (new func to avoid breaking backwards compat)
- Updated documentation
- Updated tests (100% cov for all new functionality)
@caarlos0 can you take a peek at this?

Introduce support for custom parsers + url.URL

---

README.md
env.go
env_test.go

This PR contains a few minor changes:
* Added support for time.Duration slices
* Slices are allocated in one call using make + capacity, instead of
incremental allocations through the built-in append mechanism
Arguably the latter is micro-optimisation, but seeing as it doesn't add
complexity, and is more efficient, there isn't really an argument
against it.

Add time.Duration slice support

---

env.go
env_test.go

We can't add custom parsers, since unint64 is a primitive and not a struct, this PR adds support for parsing uint64 and slices of uint64.

support uint64 and []uint64

---

env.go
env_test.go

Sometimes you end up with having types in your config that are essentially `int` or `string`. An example of this would be log levels. I'm using logrus, and would like to be able to set `LOG_LEVEL=debug`, and map it directly on to my config struct:
```go
type Config struct {
LogLevel logrus.Level `env:"LOG_LEVEL" envDefault:"debug"`
}
func logLevelParser(v string) (interface{}, error) {
return logrus.ParseLevel(v)
}
func Get() (*Config, error) {
c := &Config{}
parsers := env.CustomParsers{
reflect.TypeOf(logrus.GetLevel()): logLevelParser,
}
if err := env.ParseWithFuncs(c, parsers); err != nil {
return nil, err
}
return c, nil
}
```
I like the custom parser support, but I think it would be even better still if we could add parser functions for basic types (ie non-struct types). Hence the …

Expand support for custom parsers to non-struct types

---

env.go

--- working in a project right now where we want to log the env-vars on-service-startup, and also present them in a "service self-description API endpoint".
Since this is already relying on your neat `env` package, it would be ugly to recreate your existing `reflect` traversals for our purposes here. With this new optional general-purpose callback `OnEnvVarSet(field, value)` anyone can easily achieve such (or similar, or other) custom-requirements with `env`  =)
The first commit in here is not pertinent, simply some minor hygiene. The second commit is the meat of this PR, as per above.

Adding a general-purpose, optional zero-overhead per-field convenience callback:

---

env.go
env_test.go

Support arbitrary types by adding the ability to deserialize environment variables on any type that implements encoding.TextUnmarshaler.
This avoids the overhead of having to write custom parser funcs.
Also:
* Eliminate duplicate handleStruct method.
* Use fmt.Errorf instead of errors.New with concatenated strings.

feat(parsing): Added encoding.TextUnmarshaler support

---

README.md
env.go
env_test.go

We are wanting to reference environment variables from existing variables.  I've added this as an `expand` option but could be part of the default behavior if that's desired.  This will look for the `${VAR}` pattern and replace with the appropriate variable if found.

Add expand option to support variable expansion

---

env.go
env_test.go

Needed to check for custom parsers before matching against basic types, since aliases of those types were matching in the switch, causing the custom parser to be ignored.

Fix uint64 alias custom parser

---

env.go
env_test.go

This commit adds nested struct support.
It allows to decompose config on sub-configs with their own interfaces
```go
type Config struct {
NestedConfig
}
type NestedConfig struct {
NestedVar string `env:"nestedvar"`
}
```
```
var cfg Config
err := env.Parse(&cfg);
```

Adds nested struct support

---

env.go
env_test.go

will have the same behavior as JSON for example, which just ignores unexported fields. I think this was the behavior at some point and was broken by mistake.
closes #82

fix: dont panic if cant set

---

env.go
env_test.go

Adds support for traversing non-defined type fields
```golang
type T struct {
NonDefinedField struct {
Foo string `env:"T_FOO"`
}
}
```

feat: support traversing non-defined type fields

---

.travis.yml

test: Run tests on Go 1.13
This PR updates travis to run the test suite on Go 1.13 which is the current stable Go version

test: run tests on Go 1.13

---

env.go

* Remove yoda style expression `if nil != err`.
* Change `strings.ToLower` comparison to `strings.EqualFold` for optimal strings/bytes case-insensitive comparison.
* Remove useless `len()` check.

refactor: small code improvement

---

README.md
env.go
env_test.go

We use github.com/caarlos0/env for config in our docker containers, as I expect many do. 
In this context it would be helpful be able to load configuration content from a files instead of environment variables in some cases.
Eg. instances where PEM files are needed and files are mounted into a docker container instead of added into the environment variables  
intended use would be 
```bash
env PRIVATE_RSA_KEY=key-to-be-overwritten \
PRIVATE_RSA_KEY_FILE=/path/to/secret/rsa/key.pem
```
```go
type config struct {
PrivRSAKey string `env:"PRIVATE_RSA_KEY,file"`
}
```
If `PRIVATE_RSA_KEY_FILE` is provided it will prefer the content in that file over the environment variable

feat: Support to load values from file

---

env.go
env_test.go

fix: fix typos in defaultTypeParsers

---

README.md
env.go
env_test.go

This kind of slipped through on the last PR. 
But as of now. If the file annotation, that variable implicitly becomes requierd in order not to produce an error.
For my original usecase ex. 
```go
type Client struct {
ClientCert     string   `env:"CLIENT_CERT"`
ClientCertFile string   `env:"CLIENT_CERT_FILE,file"`
...
```
If i choose to use CLIENT_CERT and CLIENT_CERT_FILE is left empty, it will produce an error 
see https://github.com/caarlos0/env/blob/master/env_test.go#L1108
This PR should fix this and give it more of an expected behavior using required for this instead.

fix: Env variables annotated with file is not allowed to be empty

---

env.go
env_test.go

Custom slice types never reach their `ParseFunc` because they get treated as "normal" slice types, the issue was mentioned here: https://github.com/caarlos0/env/issues/110
An easy fix is to move handling slices to after custom parse functions, do you think there are any downsides to that?

fix: support custom slice types

---

README.md

Godoc badge from README points to http://godoc.org/github.com/caarlos0/env, which redirects to https://pkg.go.dev/github.com/caarlos0/env and contains information about an old version of this package.
This MR fixes this by appending v6 suffix to godoc link.

Update godoc link

---

.github/workflows/build.yml
env_test.go

This issue was found in Ubuntu as you can see here:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-hirsute/hirsute/amd64/g/golang-github-caarlos0-env/20210104_100201_2ced3@/log.gz

feat: upgrade to go 1.15

---

env.go
env_test.go

This adds a check (and corresponding test) to prevent rogue blank env keys in the environment from producing unexpected results on fields without `env` tags, as per #152 .

Add check for blank env key

---

.goreleaser.yml
env_test.go
env_windows_test.go
go.mod
go.sum

the idea is to lower the number of dependencies.
matryer's `is` has no dependencies, which is IMHO great for a library like `env`, which aims to be "minimal but effective".

test: replace testify with is

---

env.go
env_test.go

Changes
===
- Add a new option `RequiredIfNoDef` that mark all field `,required` by default.
Why
===
In most of my projects, environement variables are either required or have default values. 
Adding this option allow to remove a redundant (and sometimes obvious) `,required` in field tags.

feat: Add option: 'required' by default

---

README.md

Small spelling issue on "empty"

docs: Fix spelling in readme

---

README.md
env.go
env_test.go

feat: onset hook

---

env.go
env_test.go

This PR follows my [previous one](https://github.com/caarlos0/env/pull/187) and fix an issue I spoted when using the option with embedded structs.
Changes
===
- Fix issue causing parse to fail on embedded struct when using `RequiredIfNoDef` option.
- Updated test related to `RequiredIfNoDef` option.

fix: error in embedded struct when using option RequiredIfNoDef:true

---

env.go
env_test.go

The io/ioutil package has been deprecated as of Go 1.16.
See https://golang.org/doc/go1.16#ioutil

refactor: move from io/ioutil to io and os package

---

env.go
env_test.go

fix: prefixes on pointers

---

env.go
env_test.go

i wrote a nested anonymouse struct config object like this:
```
type Config struct {
DB struct {
Master string `env:"MASTER"`
} `envPrefix:"DB_"`
}
```
but env failed to parse the `DB_MASTER` env variable. after investigation, I found a recursive call in the doParse() func missed passing a prefix to the opt argument, cause.
this PR wraps a `optsWithPrefix` on calling `Parse` recursively, so the `Parse` function can get the prefix which defined in the `envPrefix` tag.
the tests have been passed, but I dunno if this change could introduce any side effect or not. Thank you for advice!
regards

fix: pass prefix on anonymous struct

---

env.go

* `nil` check line removed from the `newParserError`function. Because it is called from other functions after checking the `err` whether its value is `nil`. That's why no need to check it again inside the function.
* This change will also increase the code coverage from 98.2% to 98.7% with Go's code coverage metrics.
* This line is one of the two uncovered lines wrt [codecov](https://app.codecov.io/gh/caarlos0/env/blob/main/env.go).
Signed-off-by: Gökhan Özeloğlu <gozeloglu@gmail.com>

refactor: remove unnecessary line

---

env.go
env_test.go

we were modifying the map, not it returns from a function, so it's always a fresh copy and there's no way to get into race conditions there.
also improved tests so they don't mess with each other too much, also ensuring they cleanup their envs after.
closes #222

fix: race condition in ParseWithFuncs

---

env.go
env_test.go

fixes #226 
it was not passing down the funcmap to the children anon structs, which was causing a weird error in this particular case.

fix: custom parsers with anon inner structs

---

env.go
env_test.go

I think, we simply need to check not if the `key` (which is `prefix + key`) is empty, but if the `key` itself. For this, I introduced variable `ownKey`. All other usages of `key` remained the same. All tests have passed and I added my own test to cover this bug.

fix: RequiredIfNoDef with nested structs

---

env.go
env_test.go

Hello,
The purpose of this PR is to implement Enhancement #232
This allows aggregating errors from parsing, so if you have multiple missing variables it prints like: "env: required environment variable "NAME" is not set; env: required environment variable "FRUIT" is not set". 
The idea is to refactor a method doParse() by moving out all parsing process to a separate method doParseField(). In that case doParseField() may return an error per field hence doParse() may accumulate errors
Do let me know if any changes are required

Error aggregation

---

env.go
env_test.go

This is a fix for the bug #235 
I can't understand the purpose of condition !refField.IsNil() but for this use case it was considering it as non empty value (line 229), calling ParseWithFuncs (line 234) and failing due to non struct type (line 190).
I have removed it and added extra tests for that use case and all UTs are ok
@caarlos0  can you please take a look?

Fix non empty struct pointer value

---

README.md

I'm not sure if this is just a typo but I think the following was intended.
Change the explanation of required tag from:
>  While `required` demands the environment variable to be check, it doesn't check its value.
to:
>  While `required` demands the environment variable to be set, it doesn't check its value.
Thanks for "env".

Fix minor typo in readme file?

---

env.go
env_test.go

Thanks for creating this package which is simple and elegant. We are adopting this, and most of things go well except support for map.
There is a use case from us, e.g.
```go
type config struct {
MapStringString map[string]string `env:"MAP_STRING_STRING" envSeparator:","`
MapStringInt64  map[string]int64  `env:"MAP_STRING_INT64"`
MapStringBool   map[string]bool   `env:"MAP_STRING_BOOL" envSeparator:";"`
}
```
Currently we handle this by a self-defined ParserFunc, and I think it would be great if this package can support basic types of map handling.
I'm not sure if this PR is suitable for this package, if yes, I will commit about README additionally. 😃

feat: support map kind env

---

README.md
env_test.go
error.go

allow to use `errors.Is` on `AggregateError`s.
refs #233

feat: implement Is on AggregateError

---

README.md
env.go
env_test.go
go.mod

- This replaces the `ParseWithFuncs` function with a `ParseWithOptions`. 
- In addition to that, `Parse` does not accept any `Options` anymore.
- It's now also very explicit that the caller should pass only one `Options` parameter.
- `FuncMap` is now a field of `Options`.
- This allowed to refactor quite a bit, improving readability here and there, as well as making the surfacing API simpler and more obvious.
- This is a breaking change, so this also bumps the mod to v8.
Migration process:
- if you use `env.Parse` with no options, no change is required.
- if you use `env.Parse` with one `Options{}`, call `env.ParseWithOptions` instead. 
- if you use `env.Parse` with options, and pass more than one `Options`, merge them into a single one, and use `env.ParseWithOptions` instead.
- if you …

feat!: remove ParseWithFuncs, add ParseWithOptions

---

.github/workflows/build.yml

always test in the last 2 versions of go

build: test on go stable and oldstable

---

env.go

Options.OnSet gets called on _all_ fields, even the ones that _don't_ have an `env` key defined. This simply ignore those.
Example: https://go.dev/play/p/U0dET0zgYto
```go
package main
import (
"fmt"
"log"
"github.com/caarlos0/env/v8"
)
type User struct {
Name     string `env:"NAME"`
Password string `env:"PASSWORD"`
}
type Config struct {
User     User   `envPrefix:"USER_"` // this shouldn't be passed to OnSet
Username string `env:"USERNAME" envDefault:"admin"`
Password string `env:"PASSWORD"`
}
func main() {
cfg := &Config{}
opts := env.Options{
Prefix: "ENVENV_",
OnSet: func(tag string, value interface{}, isDefault bool) {
fmt.Printf("Set %s to %v (default? %v)\n", tag, value, isDefault)
},
}
// Load env vars.
if err := env.ParseWithOptions(cfg, opts); err != nil {
log.Fatal(err)
}
// …
```

fix: skip fields without env key in onSet

---

README.md
env.go
env_test.go
error.go

BREAKING CHANGE: this replaces the `envExpand` tag with the `expand` option to the `env` tag, to be more consistent with other boolean options.
closes #262

feat!: accept expand as an option to the env tag

---

env_tomap.go
env_tomap_test.go
env_tomap_windows.go
env_tomap_windows_test.go

Check the validity of environment variables when splitting variables by `=`. Ignore environment variables that don't include an `=` sign.

fix: invalid environment variable

---

env.go
env_test.go

Here's example implementation for #260, not really sure about names I used :)

Add GetFieldParams and GetFieldParamsWithOptions functions

---

env.go
env_test.go

This small fix/feature adds the ability to override default **ParserFunc** in **Options{FuncMap}** for **ParseWithOptions**
**When it can be useful:**
When for some reason you can't use default **ParseDuration** format but want to have a **time.Duration**
Like today I ran into a small but very annoying problem
I had some executions like `INTERVAL=1 ./script.sh` and wanted to override **time.Duration** parser but it was not possible. 
We may also want to override the **URL** parser or some other future **defaultTypeParsers**

ParseWithOptions: add the ability to override defaultTypeParsers

---

README.md
env.go
env_test.go

We have use cases, when we would use ":" as a map value. For example,in the case of "default:http://example.com/," this functionality is currently unavailable due to the ":" character being reserved as a separator between keys and values. This pull request solves the problem.
If you have any suggestions for a more suitable name instead of `envKeyValSeparator`, please feel free to share

feat: custom key value separator

---

README.md
env.go
env_test.go

resolves #279 (and resolves #250 (?))
To capture the default values when expanding envs, we need to somehow have access to the previously resolved variables.
So, the `get()` function needs an auxiliar data structure (`map[string]string`) that will keep track of the resolved raw strings. In that way, we can take advange of `os.Expand(s string, mapping func(string) string)` to provide our own mapping function that returns the resolved string value for a given key.
To avoid passing this auxiliar data structure as a parameter down the function calls, I added it as an unexported field of the Options struct, let's say, using `opts` as if it were a `ctx`.
I'm not really sure if it's the best way of doing this, any suggestions will be more than appreciated!
edit: typo

enhancement: Expand with default values

---

env.go
env_test.go

fix: UseFieldNameByDefault when uppercased word in name

---

env.go
env_test.go

This commit fixes the nil pointer structs. 
If a struct pointer field is **nil**, it will be initialised first & then used for further processing.

#234 - fix: add logic to handle nil pointer structs

---

README.md
env.go
env_test.go
go.mod

as it would automatically initialize nil pointers.
this retracts that version, and gate this new feature behind an `init` tag option.
closes #317
closes #310
refs  #306
refs #234

fix: retract v11.0.1, gate init nil pointers

---

README.md
env.go
env_test.go

feat: mapping slice of complex struct. [#298](https://github.com/caarlos0/env/issues/298)

feat: mapping slice of complex struct

---

env.go
env_test.go
go.mod

fix: do not init empty arrays

---

env.go
env_test.go
error.go
example_test.go

fix: improve errors

---

env.go
env_test.go

We can change the "env" to some other tag name using opt.TagName. I think that it will be more consistent to have an opt.DefaultTagName to change the tag for "envDefault".
That could help switching from other env libraries.

Support other names for envDefault

---

error.go

implement interface { Unwrap() []error } for AggregateError to be compatible with std errors.Join go1.20 without any breaking change
some errors handling packages respect to this interfaces like github.com/itsabgr/ge

implement interface { Unwrap() []error }  for AggregateError

---

env.go
env_test.go

We can change "env" or "envDefault" to some other tag name. I think it would be more consistent to have opt.PrefixTagName to change the tag to "envPrefix".
This might help when migrating from other environment libraries.

Support custom tag name for envPrefix

---

.golangci.yml
env.go
env_test.go
error.go
example_test.go

The PR enables [`gocritic`](https://golangci-lint.run/usage/linters/#gocritic) in golangci-lint's config and fixes appeared lint issues:
```
❯ golangci-lint run
env.go:606:40: emptyStringTest: replace `len(fieldParams.OwnKey) > 0` with `fieldParams.OwnKey != ""` (gocritic)
if fieldParams.Required && !exists && len(fieldParams.OwnKey) > 0 {
^
env.go:266:12: evalOrder: may want to evaluate Parse(&t) before the return statement (gocritic)
return t, Parse(&t)
^
env.go:273:12: evalOrder: may want to evaluate ParseWithOptions(&t, opts) before the return statement (gocritic)
return t, ParseWithOptions(&t, opts)
^
env.go:641:1: paramTypeCombine: func(key, defaultValue string, defExists bool, envs map[string]string) (val string, exists bool, isDefault bool) could be replaced with func(key, …
```

refactor: enable gocritic linter and fix lint issues

---

env_test.go

In TestParsesEnv test case, there is no FOO environment variable, so it cannot test whether the unexported field is set successfully

fix: field 'unexported' has no environment variable

---

README.md
env.go
env_test.go

1. If the environment variable key specified in env does not exist in the environment variables, and the key specified in envDefault is in the format of "${var}" or "$var", after being read, it is not replaced with the desired value.
2. the merging of customOptions and options has been written as the mergeOptions function.
I’m not sure if you accept these two commits.

The expand logic for env tag options has been modified, and the customOptions function has been refactored

---

env.go
env_test.go
example_test.go

I've encountered scenarious of loading config from file and then applying env vars.
Would be nice to ignore defaults for thouse values already set.

Options to set defaults for zero values only
